routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'AdminController');
    Route::any('users/dt', 'AdminController@datatable')->name('users.datatable');
    Route::get('user/profile', 'AdminController@profile')->name('user.profile');
    Route::post('user/profile', 'AdminController@profilePost')->name('user.profile.post');
    Route::post('user/profile/avatardelete', 'AdminController@avatarDelete')->name('user.avatardelete');


    Route::post('changeAdminLanguage', 'HomeController@changeAdminLanguage')->name('language.change');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');

    Route::resource('ranks', 'RankController');
    Route::any('ranks/dt', 'RankController@datatable')->name('ranks.datatable');

    Route::resource('officers', 'OfficerController');

    // Route::get('officers', 'OfficerController@index')->name('officer.index');
    // Route::post('officers/store', 'OfficerController@store')->name('officer.store');
    // Route::post('officers-update/{id?}', 'OfficerController@officerUpdate')->name('officer.update');

    // Route::get('form-load', ['as' => 'officer-form-load', 'uses' => 'OfficerController@formLoad']);
    // Route::get('form-load-edit/{id?}', ['as' => 'officer-form-load-edit', 'uses' => 'OfficerController@formLoadEdit']);


});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'Web\HomeController@index')->name('home');

// Login Routes...
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

    // Password Reset Routes...
    Route::get('password/request', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
});

//Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth:web','checkAdmin'], 'prefix' => 'dashboard'], function () {
    
    Route::group(['prefix' => 'officer', 'middleware' => 'auth:web'], function () {
    Route::get('home', 'Web\OfficerController@index');
        
   });

app/Rank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rank extends Model
{
    protected $table = 'ranks';

    public function rankTranslation() {
       return $this->hasMany(RankTranslation::class, 'rank_id', 'id');
   }
}

app/Http/Controllers/Admin/RankController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use App\Language;
use App\Rank;
use App\RankTranslation;
use URL;
use Auth;

class RankController extends Controller {

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('ranks_read', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['index', 'profile', 'show']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('ranks_create', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['create', 'store']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('ranks_update', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['edit', 'update']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('ranks_delete', 'admin')) {
                return $next($request);
            } else {
                return redirect()->route('admin.dashboard')
                                ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
            }
        }, ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.ranks.index');
    }

    public function datatable()
    {
        $currentUser  = Auth::guard('admin')->user();
        $isSuperAdmin = $currentUser->hasRole('super-admin', 'admin');
        $datas        = Rank::Join('rank_translations', 'ranks.id', '=', 'rank_translations.rank_id')
                        ->where('rank_translations.language_id', getdefaultLanguage()->id)
                        ->select('ranks.id', 'rank_translations.name')->orderBy('ranks.id', 'asc')->get();
        return Datatables::of($datas, $isSuperAdmin, $currentUser)
                        ->rawColumns(['actions'])
                        ->editColumn('actions', function ($datas) use ($currentUser, $isSuperAdmin) {
                            $b = '';
                            if ($isSuperAdmin || $currentUser->hasPermissionTo('ranks_update', 'admin')) {
                                $b .= '<a href="' . URL::route('admin.ranks.edit', $datas->id) . '" class="btn btn-primary btn-xs mrs"><i class="fa fa-pencil"></i></a>';
                            }
                            if ($isSuperAdmin || $currentUser->hasPermissionTo('ranks_delete', 'admin')) {
                                $b .= ' <a href="' . URL::route('admin.ranks.destroy', $datas->id) . '" class="btn btn-danger btn-xs destroy"><i class="fa fa-trash"></i></a>';
                            }
                            return $b;
                        })->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ranks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:120',
        ]);

        if (getdefaultLanguage()->id == 2) {
            return redirect()->back()->with('growl', ['You can not create arabic content first.', 'danger'])->withInput();
        }

        $exist = Rank::join('rank_translations', 'ranks.id', '=', 'rank_translations.rank_id')
                        ->where('rank_translations.name', $request->name)->first();

        if ($exist) {
            return redirect()->back()->with('growl', ['The same rank already exist.', 'danger'])->withInput();
        }

        $data      = new Rank();
        $data->save();
        $languages = Language::all();
        foreach ($languages as $language) {
            RankTranslation::create(
                    [
                        'language_id' => $language->id,
                        'rank_id'     => $data->id,
                        'name'        => $request->name
                    ]
            );
        }

        //Redirect to the users.index view and display message
        return redirect()->route('admin.ranks.index')->with('growl', ['Rank successfully added.', 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Rank::Join('rank_translations', 'ranks.id', '=', 'rank_translations.rank_id')
                        ->where('rank_translations.language_id', getdefaultLanguage()->id)
                        ->where('ranks.id', $id)
                        ->select('rank_translations.name', 'ranks.id')->first();
        return view('admin.ranks.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:120'
        ]);

        $languages = Language::get();

        $exist = Rank::Join('rank_translations', 'ranks.id', '=', 'rank_translations.rank_id')
                        ->where('ranks.id', '!=', $id)
                        ->where('rank_translations.name', $request->name)->first();
        if ($exist) {
            return redirect()->back()->with('growl', ['The same rank already exist.', 'danger'])->withInput();
        }
        $data = Rank::find($id);
        $data->save();

        $edit       = RankTranslation::where('rank_id', $id)->where('language_id', getdefaultLanguage()->id)->first();
        $edit->name = $request->name;
        $edit->save();
        return redirect()->route('admin.ranks.index')->with('growl', ['Rank successfully edited.', 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Rank::destroy($id);
    }

}

resources/views/admin/ranks/create.blade.php
@extends('adminlte::page')

@section('title', 'Add new Rank')

@section('content_header')
<h1><i class='fa fa-get-pocket'></i> Add Rank</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ url('/admin/ranks') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">
               @include('admin.ranks.form')
            </div>
        </div>
    </div>
</div>
@stop
@section('css')
     <!-- iCheck for checkboxes and radio inputs -->
     <link rel="stylesheet" href="{{asset('vendor/adminlte/plugins/iCheck/all.css')}}">
     <style media="screen">
          #preview_image {
               width: 300px !important;
               height: 101px !important;
               object-fit: cover;
          }
     </style>
@stop
@section('js')
<!-- iCheck 1.0.1 -->
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type="text/javascript">

     //iCheck for checkbox and radio inputs
     $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
     });

      $('#seperate').on('ifChecked', function(event){
           $("#arabic_image").show();
      });

      $('#seperate').on('ifUnchecked', function(event){
           $("#arabic_image").hide();
      });

     // function readURL(input) {
     //        if (input.files && input.files[0]) {
     //            var reader = new FileReader();
     //            reader.onload = function (e) {
     //                $('#preview_image')
     //                    .attr('src', e.target.result)
     //                    .width(300)
     //                    .height(101);
     //            };
     //            reader.readAsDataURL(input.files[0]);
     //        }
     //    }
</script>
@stop

resources/views/admin/ranks/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Ranks')

@section('content_header')
<h1><i class='fa fa-get-pocket'></i> Edit {{$data->title}}</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ url('/admin/ranks') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">
                @include('admin.ranks.form', ['submitButtonText' => 'Update'])
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{asset('vendor/adminlte/plugins/iCheck/all.css')}}">
@stop
@section('js')
<!-- iCheck 1.0.1 -->
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type="text/javascript">

     //iCheck for checkbox and radio inputs
     $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
     });

      $('#seperate').on('ifChecked', function(event){
           $("#arabic_image").show();
      });

      $('#seperate').on('ifUnchecked', function(event){
           $("#arabic_image").hide();
      });
</script>
 @stop

resources/views/admin/ranks/form.blade.php
@if(isset($data))
{{ Form::model($data, array('route' => array('admin.ranks.update', $data->id), 'method' => 'PUT', 'files' => 'true')) }}
@else
{!! Form::open(
  array(
      'route' => 'admin.ranks.store',
      'class' => 'form',
      'novalidate' => 'novalidate',
      'files' => 'true'))
!!}
@endif
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
   {{ Form::label('name', 'Name') }}
   {{ Form::text('name', null, array('class' => 'form-control', 'autocomplete' =>'off')) }}
   {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

{{ Form::submit(isset($submitButtonText) ? $submitButtonText : 'Create', array('class' => 'btn btn-primary')) }}

{{ Form::close() }}

resources/views/admin/ranks/index.blade.php
@extends('adminlte::page')

@section('title', 'Admin Ranks')

@section('content_header')
<h1><i class="fa fa-get-pocket"></i> Admin Ranks</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header">
                <?php $user = Auth::guard('admin')->user(); ?>
                @if($user->hasRole('super-admin','admin') || $user->hasPermissionTo('rank_create','admin'))
                    <a href="{{ route('admin.ranks.create') }}" class="btn btn-success btn-sm">Add Rank</a>
                @endif
            </div>
            <div class="box-body">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="table-id">
                        <thead>
                            <tr>
                                <th>Row No</th>
                                <th>Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>

                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@stop
@section('js')
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(function () {
    oTable = $('#table-id').DataTable({
        processing: false,
        serverSide: true,
        orderable: true,
        searchable: true,
        ajax: {
            url: '{!! route('admin.ranks.datatable') !!}',
            type: 'post',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'}
        },
        columns: [
             {
                render: function (data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                },
                searchable: false
             },
            {data: 'name', name: 'name'},
            {data: 'actions', name: 'actions', orderable: false, searchable: false}
        ]
    });

    $('#table-id').on('click', '.destroy', function (e) {
        e.preventDefault();

        var href = $(this).attr('href');

        bootbox.confirm("{{ trans('myadmin.confirm-delete') }}", function (result) {
            if (result === false)
                return;

            $.ajax({
                url: href,
                method: 'DELETE',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                success: function () {
                    oTable.ajax.reload();
                    growl("User successfully deleted.", "success");
                }
            });
        });
    });
});
</script>
@stop