routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'AdminController');
    Route::any('users/dt', 'AdminController@datatable')->name('users.datatable');
    Route::get('user/profile', 'AdminController@profile')->name('user.profile');
    Route::post('user/profile', 'AdminController@profilePost')->name('user.profile.post');
    Route::post('user/profile/avatardelete', 'AdminController@avatarDelete')->name('user.avatardelete');


    Route::post('changeAdminLanguage', 'HomeController@changeAdminLanguage')->name('language.change');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');

    Route::resource('ranks', 'RankController');
    Route::any('ranks/dt', 'RankController@datatable')->name('ranks.datatable');

    Route::resource('officers', 'OfficerController');

    // Route::get('officers', 'OfficerController@index')->name('officer.index');
    // Route::post('officers/store', 'OfficerController@store')->name('officer.store');
    // Route::post('officers-update/{id?}', 'OfficerController@officerUpdate')->name('officer.update');

    // Route::get('form-load', ['as' => 'officer-form-load', 'uses' => 'OfficerController@formLoad']);
    // Route::get('form-load-edit/{id?}', ['as' => 'officer-form-load-edit', 'uses' => 'OfficerController@formLoadEdit']);


});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'Web\HomeController@index')->name('home');

// Login Routes...
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

    // Password Reset Routes...
    Route::get('password/request', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
});

//Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth:web','checkAdmin'], 'prefix' => 'dashboard'], function () {
    
    Route::group(['prefix' => 'officer', 'middleware' => 'auth:web'], function () {
    Route::get('home', 'Web\OfficerController@index');
        
   });

app/Http/Controllers/Admin/OfficerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use App\Language;
use App\Rank;
use Hash;
use Mail;
use App\RankTranslation;
use URL;
use Auth;
use App\User;
use App\UserTranslation;
use App\Traits\ImageTraits;
use File;
use Storage;

class OfficerController extends Controller
{
        use ImageTraits;

        public function __construct()
        {
            $this->middleware(function ($request, $next) {
                $user = Auth::guard('admin')->user();
                if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('officers_read', 'admin')) {
                    return $next($request);
                } else {
                    return redirect()->route('admin.dashboard')
                                    ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
                }
            }, ['only' => ['index', 'profile', 'show']]);

            $this->middleware(function ($request, $next) {
                $user = Auth::guard('admin')->user();
                if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('officers_create', 'admin')) {
                    return $next($request);
                } else {
                    return redirect()->route('admin.dashboard')
                                    ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
                }
            }, ['only' => ['create', 'store']]);

            $this->middleware(function ($request, $next) {
                $user = Auth::guard('admin')->user();
                if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('officers_update', 'admin')) {
                    return $next($request);
                } else {
                    return redirect()->route('admin.dashboard')
                                    ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
                }
            }, ['only' => ['edit', 'update']]);

            $this->middleware(function ($request, $next) {
                $user = Auth::guard('admin')->user();
                if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('officers_delete', 'admin')) {
                    return $next($request);
                } else {
                    return redirect()->route('admin.dashboard')
                                    ->with('growl', ['Your don\'t have permission to acces this page.', 'danger']);
                }
            }, ['only' => ['destroy']]);
        }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $getRanks = Rank::Join("rank_translations as rt", "rt.rank_id", "=", "ranks.id")->where("rt.language_id", getdefaultLanguage()->id)->select("ranks.id", "rt.name")->get();
         $officers = User::with(['officerTranslation' => function ($query) { $query->where('language_id', getdefaultLanguage()->id);}, 'officerRank' => function ($query) { $query->where('language_id', getdefaultLanguage()->id);}])
                                   ->where('status', 1)->orderBy('id', 'desc')->get();
         return view('admin.officers.index', compact("getRanks", "officers"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $getRanks = Rank::join("rank_translations as rt", "rt.rank_id", "=", "ranks.id")->where("rt.language_id", getdefaultLanguage()->id)->select("ranks.id", "rt.name")->get();
         return view('admin.officers.form', compact('getRanks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $validator = \Validator::make($request->all(), [
                    'name'    => 'required',
                    'rank'    => 'required',
                    'email'   => 'required|email|unique:users',
                    'phone'   => 'required|numeric|unique:users,mobile',
                    'image' => 'required|mimes:jpeg,png,jpg|max:2048',
                        ], [
                    "image.mimes" => "The valid image type jpeg,png,jpg",
                    "image.max"   => "Image size must be less than 2MB"
        ]);
        if ($validator->fails()) {
            $errors = array_combine($validator->errors()->keys(), $validator->errors()->all());
            return response()->json(["status" => 100,'errors' => $errors]);
        }

        if (getdefaultLanguage()->id == 2) {
            return response()->json(["status" => 200,'message' => 'You can not create arabic content first']);
        }

        $password = str_random(8);

        $user = new \App\User();
        $user->email = $request->email;
        $user->password = Hash::make($password);
        $user->mobile = $request->phone;
        $user->rank_id = $request->rank;
        $user->api_token =  $this->generateApiToken();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $path = 'users/profiles/';
            $resizedImage = $this->resize($image, $path, 'officer_');
            if ($resizedImage) {
                $user->image = $resizedImage;
            }
        }
        $user->save();
        $languages = Language::all();
        foreach($languages as $lang){
            $userTraslators = new \App\UserTranslation();
            $userTraslators->name = $request->name;
            $userTraslators->user_id = $user->id;
            $userTraslators->language_id = $lang->id;
            $userTraslators->save();
        }
        try {
            $data = array('name' => $request->name, 'email' => $request->email, 'password' =>$password);
            Mail::send('emails.create_officers', $data, function($message) use ($request) {
                                       $message->from('admin@dubaipolice.com');
                                       $message->to($request->email)
                                       ->subject('Welcome Mail');
                          });
        } catch (\Exception $e) {

        }
        // $officer = User::with(['officerTranslation' => function ($query) { $query->where('language_id', getdefaultLanguage()->id);}, 'officerRank' => function ($query) { $query->where('language_id', getdefaultLanguage()->id);}])
        //                            ->where('status', 1)
        //                            ->where('id', $user->id)
        //                            ->orderBy('id', 'desc')->first();
        return response()->json(["status" => 400,'message' => 'Officer added successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $getRanks = Rank::join("rank_translations as rt", "rt.rank_id", "=", "ranks.id")->where("rt.language_id", getdefaultLanguage()->id)->select("ranks.id", "rt.name")->get();
         $data = User::Join("user_translations", "user_translations.user_id", "=", "users.id")
                             ->Join("rank_translations", "rank_translations.rank_id", "=", "users.rank_id")
                             ->where('users.id', $id)
                             ->where('user_translations.language_id', getdefaultLanguage()->id)
                             ->select('rank_translations.name as rank_name', 'user_translations.name as user_name', 'users.mobile', 'users.email', 'users.rank_id', 'users.image', 'users.id')
                             ->first();
          return view('admin.officers.form', compact('data', 'getRanks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $validator = \Validator::make($request->all(), [
                   'name'    => 'required',
                   'rank'    => 'required',
                   'email'   => 'required|email|unique:users,email,'.$id,
                   'phone'   => 'required|numeric|unique:users,mobile,'.$id,
                   'image' => 'mimes:jpeg,png,jpg|max:2048',
                       ], [
                   "image.mimes" => "The valid image type jpeg,png,jpg",
                   "image.max"   => "Image size must be less than 2 MB"
       ]);
       if ($validator->fails()) {
           $errors = array_combine($validator->errors()->keys(), $validator->errors()->all());
           return response()->json(["status" => 100,'errors' => $errors]);
       }
       $user = User::find($id);
       $user->email = $request->email;
       $user->mobile = $request->phone;
       $user->rank_id = $request->rank;

       if($request->hasFile('image')) {
           $image = $request->file('image');
           $path = 'users/profiles/';
           $resizedImage = $this->resize($image, $path, 'officer_');
           if ($resizedImage) {
               if (!env('CDN_ENABLED', false)) {
                   File::delete(public_path('uploads/' . $path) . $user->image);
               } else {
                   Storage::disk('s3')->delete(env('CDN_FILE_DIR', 'dev/path/uploads/') . $path . $user->image);
               }
               $user->image = $resizedImage;
           }
       }
       $user->save();

       $edit  = UserTranslation::where('user_id', $id)->where('language_id', getdefaultLanguage()->id)->first();
       $edit->name = $request->name;

app/Http/Controllers/Web/OfficerController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class OfficerController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \App\User::join("user_translations as ut","ut.user_id","=","users.id")
                ->where("users.id",Auth::guard("web")->user()->id)
                ->where("ut.language_id",getdefaultLanguage()->id)
                ->select("ut.name","users.image")
                ->first();
        return view('dashboard.home', compact("user"));
    }
}

resources/views/admin/officers/form.blade.php
<form id="user-form" enctype="multipart/form-data" action="@if(isset($data)) {{route('admin.officers.update', $data->id)}} @else{{route('admin.officers.store')}}@endif" method="post">
     @if(isset($data))
     <input name="_method" type="hidden" value="PUT">
     @endif
    {{ csrf_field() }}
     <div class="modal-header text-center">
         <div class="image-wrapper">
            <input type="file" name="image" id="imgupload" style="display: none">
            @if(isset($data))
            <img class="card-img-top profile-img myImg" id="OpenImgUpload" src="{{url(asset('uploads/users/profiles/'.$data->image))}}" alt="Officer">
            @else
            <img class="card-img-top profile-img myImg" id="OpenImgUpload" src="{{url(asset('images/police.jpg'))}}" alt="Officer">
            @endif
         </div>
         <p id="image" class="cls_errror validation_error" style="display:none;"></p>
     </div>
     <div class="form-group">
         <label>Officer Name</label>
         <input type="text" name="name" class="form-control" value="@if(isset($data)){{$data->user_name}}@endif">
         <p id="name" class="cls_errror validation_error" style="display:none;"></p>
     </div>
     <div class="form-group">
         <label>Officer Rank</label>
         <select class="form-control" name="rank">
            <option value="">Select a Rank</option>
            @foreach($getRanks as $rank)
            <option @if(isset($data)) @if($data->rank_id == $rank->id) selected @endif @endif value="{{$rank->id}}">{{$rank->name}}</option>
            @endforeach
         </select>
         <p id="rank" class="cls_errror validation_error" style="display:none;"></p>
     </div>
     <div class="form-group">
         <label>Officer Email</label>
         <input type="email" name="email" class="form-control" value="@if(isset($data)){{$data->email}}@endif">
         <p id="email" class="cls_errror validation_error" style="display:none"></p>
     </div>
     <div class="form-group">
         <label>Officer Phone</label>
         <input type="text" name="phone" class="form-control" value="@if(isset($data)){{$data->mobile}}@endif">
         <p id="phone" class="cls_errror validation_error" style="display:none"></p>
     </div>
 <div class="modal-footer d-flex justify-content-center">
     <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
     <button type="submit" name="button" class="btn btn-success btn-add">@if(isset($data)) Update @else Add @endif</button>
 </div>
</form>

resources/views/admin/officers/index.blade.php
@extends('adminlte::page')

@section('title', 'Officer')

@section('content_header')
<h1><i class="fa fa-get-pocket"></i> Officers</h1>
@stop
@section('content')
<div class="row">

    <div class="col-md-12">
        <div class="show-users">

        </div>
        @if(!$officers->isEmpty())
        @foreach($officers as $officer)
        <div class="col-md-4 officer_block">
            <div class="card card-background officers-lists">
                 <div class="manage-btn">
                      <ul class="menu">
                           <li class="expanded">
                                <a href="#"><i class="fa fa-ellipsis-v"></i></a>
                                <ul class="sub-menu">
                                     <li><a href="#"  data-toggle="modal" data-target="#modalOfficerCreate"  data-href="{{route('admin.officers.edit', $officer->id)}}">Edit</i></a></li>
                                     <li><a href="{{route('admin.officers.destroy', $officer->id)}}" class="destroy">Delete</a></li>
                                     <li><a href="#">Assign</a></li>
                                </ul>
                           </li>
                      </ul>

                 </div>
                <img class="card-img-top profile-img" src="{{url(asset('uploads/users/profiles/'.$officer->image))}}" alt="Officer">
                <div class="officer-datas">
                     <h2>{{$officer->officerTranslation[0]->name}}</h2>
                     <h3>{{$officer->officerRank[0]->name}}</h3>
                     <p class="phone">Phone: {{$officer->mobile}}</p>
                     <p class="email">Phone: {{$officer->email}}</p>
                </div>
            </div>
        </div>
        @endforeach
        @endif
        <div class="col-md-4">
            <div class="card card-background" style="text-align: center;padding: 90px;">
                <img class="card-img-top profile-img" src="{{url(asset('images/police.jpg'))}}" alt="Officer">
                <div class="card-body" style="margin-top: 20px;padding-bottom: 50px;" data-toggle="modal" data-target="#modalOfficerCreate" data-href="{{route('admin.officers.create')}}">
                    <div class="add-button">
                        <i class="fa fa-fw fa-plus add-icons"></i>
                    </div>
                    <p class="add-p" >Add Officer</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalOfficerCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document" style="width: 300px;">
        <div class="modal-content">

            <div class="modal-body col-md-12">

            </div>
        </div>
    </div>
</div>
<div class="loading" style="display: none;">Loading&#8230;</div>
@stop
@section('css')
     <link rel="stylesheet" href="{{asset('css/loader.css')}}">
     <style media="screen">
          .officers-lists {
               background: #fff;
               padding: 35px;
               border: 3px solid #ddd;
               text-align: center;
               position: relative;
               margin-bottom: 30px;
          }
          .phone, .email {
               text-align: left;
          }
          .manage-btn {
               position: absolute;
               top: 10px;
               right: 20px;
               font-size: 25px;
          }
          ul.menu li {
               list-style: none;
          }
          ul.menu li.expanded {
               list-style: none;
               position: relative;
          }
          .manage-btn ul.sub-menu {
               border: 1px solid red;
               position: absolute;
               right: 10px;
               top: 10px;
               background: #FFF;
               border:  1px solid #333;
               padding: 0;
               display: none;
          }
          .manage-btn ul.sub-menu li {
               border-bottom: 1px solid #333;
               width: 130px;
               line-height: 1;
               padding-bottom: 10px;
          }
          .manage-btn ul.sub-menu li:last-child {
               border-bottom: none;
               width: 130px;
          }
          .manage-btn ul.sub-menu li a {
               font-size: 13px;
               color: #333;
          }
          .modal-body {
               background: #FFF;
          }
     </style>
@stop
@section('js')
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(document).ready(function () {
     $("#modalOfficerCreate").on("click", "#OpenImgUpload", function(){
        $('#imgupload').trigger('click');
    });

    $('#modalOfficerCreate').on('show.bs.modal', function (e) {
         $('.loading').show();
        var url = $(e.relatedTarget).attr('data-href');
        $.ajax({
            url: url,
            context: this,
            method: "GET",
            dataType: "html",
            beforeSend: function () {
                //$('.ajax-loading').show();
            },
            success: function (response) {
                $(this).find('.modal-body').html(response);
                $('.loading').hide();
                // $('.loading').hide();
            },
            complete: function () {
                 $('.loading').hide();
                //$('.ajax-loading').hide();
            }
        });
    });

    $(document).on("submit", "form", function (e) {
        $('.loading').show();
        e.preventDefault();

        $this = this;
        var form = new FormData($this);
        // var image = $('#imgupload').prop('files')[0];
        // console.log(image);
        // form.append('image', image);
        var url = $(this).attr('action');
        $.ajax({
            url: url,
            processData: false,
            contentType: false,
            type: 'POST',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
            data: form,
            success: function (responce) {
                if (responce.status == "100") {
                    $(".cls_errror").css("display", 'none');
                    $.each(responce.errors, function (key, value) {
                        $('#' + key).css("display", '').html(value);
                    });
                     $('.loading').hide();
                }
                if (responce.status == "200") {
                      $('.loading').hide();
                     $('#modalOfficerCreate').modal('hide');
                    growl(responce.message, "danger");
                }
                if (responce.status == "400") {
                     $('#modalOfficerCreate').modal('hide');
                      $('.loading').hide();
                    growl(responce.message, "success");
                    location.reload();
                }
            }
        });
    });
});
function imageIsLoaded(e) {
    $('.myImg').attr('src', e.target.result);
}
;
function getFile(filePath) {
    return filePath.substr(filePath.lastIndexOf('\\') + 1).split('.')[0];
}


$(":file").change(function () {
    if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = imageIsLoaded;
        reader.readAsDataURL(this.files[0]);
    }
});

$('.menu').children().click(function(){
    event.preventDefault();
    $(this).children('.sub-menu').slideToggle('slow');
});

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#OpenImgUpload').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#modalOfficerCreate").on("change", "#imgupload", function(){
    readURL(this);
});

$('.menu').on('click', '.destroy', function (e) {
   e.preventDefault();
   var outer = $(this).parent().parent().parent().parent().parent().parent().parent();
   var href = $(this).attr('href');
   bootbox.confirm("Do you want to delete this one", function (result) {
        if (result === false)
            return;

        $.ajax({
            url: href,
            method: 'DELETE',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
            success: function () {
                 outer.hide();
                 growl("Officer successfully deleted.", "success");
            }
        });
   });
});

</script>
@stop

resources/views/admin/officers/profile.blade.php
<div class="col-md-4 ">
    <div class="btn-group" style="float: right;padding-top: 20px;margin-right: 20px;">

        <!-- Basic dropdown -->
        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size: 20px;color: black"><i class="fa fa-fw fa-ellipsis-v"></i></a>

        <div class="dropdown-menu" style="">
            <li class="dropdown-lists">Edit</li>
            <li class="dropdown-lists">Delete</li>
            <li class="dropdown-lists">Assign</li>
        </div>
        <!-- Basic dropdown -->

    </div>
    <div class="card card-background" style="text-align: center">

        <img class="card-img-top profile-img" src="{{url(asset('images/police.jpg'))}}" alt="Officer">
        <div class="card-body">
            <h3 class="card-title">Ubaid Nk</h3>
            <h5 class="card-title">Rank</h5>
            <h4 class="card-text">Exhibition</h4>
            <p>International K9 Summit Dubai</p>
            <p>Phone:1234444</p>
            <p>Email:officer@gmail.com</p>
        </div>
    </div>
</div>